version: '3'
services:
  shortly_web_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: shortly_web_test
    ports:
      - '5000:5000'
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
      - ./.env.test:/usr/src/app/.env.test
      - ./.eslintrc.cjs:/usr/src/app/.eslintrc.cjs
      - ./index.html:/usr/src/app/index.html
      - ./README.md:/usr/src/app/README.md
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.node.json:/usr/src/app/tsconfig.node.json
      - ./jest.config.js:/usr/src/app/jest.config.js
      - ./vite.config.ts:/usr/src/app/vite.config.ts
      - ./cypress.config.ts:/usr/src/app/cypress.config.ts
