export { default as BrandRecognitionIconSVG } from './icon-brand-recognition.svg?react'
export { default as DetailedRecordsIconSVG } from './icon-detailed-records.svg?react'
export { default as FullyCustomizableIconSVG } from './icon-fully-customizable.svg?react'
export { default as WorkingIllustrationSVG } from './illustration-working.svg?react'
export { default as LogoSVG } from './logo.svg?react'
